project:
  type: website
  output-dir: docs

website:
  title: "Estephanie's R portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/emorales65/first_ever_blog.git
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: slate
    css: styles.css

editor: visual

